name: Build
on:
  push:
    branches: [ main ]
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate build info
        run: ./generate-build-info.sh

      - name: Generate keystore
        run: ./generate-keystore.sh

      - name: Build with sbt
        run: sbt clean assembly

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          # TODO: Change the docker credentials
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push service
        working-directory: .
        # TODO: Change the docker image name
        run: |
          docker build -t lambesh/spring-boot-scala-template .
          docker push lambesh/spring-boot-scala-template

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: ‘spring-boot-scala-template-1.0-${{ github.run_id }}.jar'
          path: target/spring-boot-scala-template*.jar

      - name: Check Out Repo
        uses: actions/checkout@v2